# Generated by Django 5.2.4 on 2025-07-14 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('JURISTE', 'Jurist'), ('RH', 'Rh'), ('MANAGER', 'Manager')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contentieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('subject', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT')], max_length=50)),
                ('juridiction_steps', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(blank=True, related_name='contentieux_actions', to='praevia_api.action')),
            ],
            options={
                'db_table': 'contentieux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'CERTIFICAT_MEDICAL'), ('ARRET_TRAVAIL', 'ARRET_TRAVAIL'), ('TEMOIGNAGE', 'TEMOIGNAGE'), ('DECISION_CPAM', 'DECISION_CPAM'), ('EXPERTISE_MEDICALE', 'EXPERTISE_MEDICALE'), ('LETTRE_RESERVE', 'LETTRE_RESERVE'), ('CONTRAT_TRAVAIL', 'CONTRAT_TRAVAIL'), ('FICHE_POSTE', 'FICHE_POSTE'), ('RAPPORT_ENQUETE', 'RAPPORT_ENQUETE'), ('NOTIFICATION_TAUX', 'NOTIFICATION_TAUX'), ('COURRIER', 'COURRIER'), ('AUTRE', 'AUTRE')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contentieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_list', to='praevia_api.contentieux')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentieux',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='contentieux_documents', to='praevia_api.document'),
        ),
        migrations.CreateModel(
            name='DossierATMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('A_ANALYSER', 'A_ANALYSER'), ('ANALYSE_EN_COURS', 'ANALYSE_EN_COURS'), ('CONTESTATION_RECOMMANDEE', 'CONTESTATION_RECOMMANDEE'), ('CONTESTATION_NON_RECOMMANDEE', 'CONTESTATION_NON_RECOMMANDEE'), ('CLOTURE_SANS_SUITE', 'CLOTURE_SANS_SUITE'), ('TRANSFORME_EN_CONTENTIEUX', 'TRANSFORME_EN_CONTENTIEUX')], default='A_ANALYSER', max_length=50)),
                ('entreprise', models.JSONField()),
                ('salarie', models.JSONField()),
                ('accident', models.JSONField()),
                ('temoins', models.JSONField(default=list)),
                ('tiers_implique', models.JSONField(blank=True, null=True)),
                ('service_sante', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dossiers', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='dossier_atmp_documents', to='praevia_api.document')),
            ],
            options={
                'db_table': 'dossiers_atmp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentieux',
            name='dossier_atmp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contentieux_detail', to='praevia_api.dossieratmp'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50)),
                ('decision', models.CharField(blank=True, choices=[('CONTEST', 'CONTEST'), ('DO_NOT_CONTEST', 'DO_NOT_CONTEST'), ('NEED_MORE_INFO', 'NEED_MORE_INFO'), ('REFER_TO_EXPERT', 'REFER_TO_EXPERT')], max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('checklist', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_performed', to=settings.AUTH_USER_MODEL)),
                ('dossier_atmp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_detail', to='praevia_api.dossieratmp')),
            ],
            options={
                'db_table': 'audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
